/* Palette generated by Material Palette - materialpalette.com/blue/light-blue */

const Colors = {
  darkPrimaryColor: "#1976D2",
  defaultPrimaryColor: "#2196F3",
  lightPrimaryColor: "#BBDEFB",
  accentColor: "#03A9F4",
  primaryTextColor: "#212121",
  secondaryTextColor: "#757575",
  dividerColor: "#BDBDBD",
  whiteText: "#FFFFFF",
};
export default Colors;
